version: '3.4'

services:
  ingress:
    build: ./ingress
    ports:
      - 9999:9999

  dex:
    image: dexidp/dex:v2.28.0
    ports:
      - 5556:5556
      - 5557:5557
      - 5558:5558
    volumes:
      - ./dex:/etc/dex
    networks:
      - roachnet
    environment:
      DEX_USER: $DEX_USER
      DEX_PASS: $DEX_PASS
    depends_on:
      - roach1
      - roach2
      - roach3

  rouch_cert_load:
    image: busybox
    volumes:
      - ./cert:/cockroach/source
      - roach_certs:/cockroach/target
    command:
      - sh
      - -c
      - "cp /cockroach/source/* /cockroach/target && chmod 700 /cockroach/target/*"


  roach1:
    image: cockroachdb/cockroach:v20.2.6
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach1-data:/cockroach/cockroach-data
      - roach_certs:/cockroach/.cockroach-certs/:ro
    networks:
      - roachnet
    depends_on:
      - rouch_cert_load
    command:
      - start
      - --certs-dir=/cockroach/.cockroach-certs/
      - --accept-sql-without-tls
      - --advertise-addr=roach1
      - --join=roach1,roach2,roach3


  roach2:
    image: cockroachdb/cockroach:v20.2.6
    volumes:
      - roach2-data:/cockroach/cockroach-data
      - roach_certs:/cockroach/.cockroach-certs/:ro
    networks:
      - roachnet
    depends_on:
      - rouch_cert_load
    command:
      - start
      - --certs-dir=/cockroach/.cockroach-certs/
      - --accept-sql-without-tls
      - --advertise-addr=roach2
      - --join=roach1,roach2,roach3

  roach3:
    image: cockroachdb/cockroach:v20.2.6
    volumes:
      - roach3-data:/cockroach/cockroach-data
      - roach_certs:/cockroach/.cockroach-certs/:ro
    networks:
      - roachnet
    depends_on:
      - rouch_cert_load
    command:
      - start
      - --certs-dir=/cockroach/.cockroach-certs/
      - --accept-sql-without-tls
      - --advertise-addr=roach3
      - --join=roach1,roach2,roach3

networks:
  roachnet:

volumes:
  roach1-data:
  roach2-data:
  roach3-data:
  roach_certs:

